"""add client contact

Revision ID: 226a00304d91
Revises: 5f684cefa828
Create Date: 2026-03-30 21:09:25.101093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '226a00304d91'
down_revision: Union[str, Sequence[str], None] = '5f684cefa828'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shipment', 'client_contact_email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shipment', 'client_contact_email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
