"""add client contact

Revision ID: 5f684cefa828
Revises: f637546de3eb
Create Date: 2026-03-07 21:40:44.409436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '5f684cefa828'
down_revision: Union[str, Sequence[str], None] = 'f637546de3eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipment', sa.Column('client_contact_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('shipment', sa.Column('client_contact_phone', sa.Integer(), nullable=True))
    op.alter_column('shipmentevent', 'status',
               existing_type=postgresql.ENUM('placed', 'in_transit', 'out_for_delivery', 'delivered', name='shipmentstatus'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shipmentevent', 'status',
               existing_type=postgresql.ENUM('placed', 'in_transit', 'out_for_delivery', 'delivered', name='shipmentstatus'),
               nullable=True)
    op.drop_column('shipment', 'client_contact_phone')
    op.drop_column('shipment', 'client_contact_email')
    # ### end Alembic commands ###
