"""add user email_verified

Revision ID: 930334c5596c
Revises: 226a00304d91
Create Date: 2026-04-04 15:53:53.747984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '930334c5596c'
down_revision: Union[str, Sequence[str], None] = '226a00304d91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipmentevent')
    op.add_column('delivery_partner', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.add_column('seller', sa.Column('email_verified', sa.Boolean(), nullable=True))

    op.execute("UPDATE delivery_partner SET email_verified = true")
    op.execute("UPDATE seller SET email_verified = true")

    op.alter_column('delivery_partner', 'email_verified', nullable=False)
    op.alter_column('seller', 'email_verified', nullable=False)


    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seller', 'email_verified')
    op.drop_column('delivery_partner', 'email_verified')
    op.create_table('shipmentevent',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('location', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('placed', 'in_transit', 'out_for_delivery', 'delivered', name='shipmentstatus'), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('shipment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipment.id'], name=op.f('shipmentevent_shipment_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('shipmentevent_pkey'))
    )
    # ### end Alembic commands ###
